name: Publish docs

on:
  workflow_dispatch: {}
  push:
    branches:
      - netlify-action
  release:
    types:
      - published
jobs:
  publish-docs:
    name: Publish docs to Netlify
#    if: ${{ !github.event.release.prerelease }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jsmrcaga/action-netlify-deploy@v1.7.2
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Triggered by release v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
